package eventplanner.features.event.dto.request;

import eventplanner.features.event.enums.RecurrenceEndType;
import eventplanner.features.event.enums.RecurrencePattern;
import eventplanner.features.event.enums.SeriesUpdateScope;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

/**
 * Request DTO for updating an event series.
 */
@Schema(description = "Request to update an event series")
@Getter
@Setter
public class UpdateEventSeriesRequest {

    // ==================== UPDATE SCOPE ====================

    @Schema(description = "Scope of the update - what events should be affected", 
            example = "THIS_AND_FUTURE", defaultValue = "THIS_AND_FUTURE")
    private SeriesUpdateScope updateScope = SeriesUpdateScope.THIS_AND_FUTURE;

    // ==================== SERIES INFO ====================

    @Size(max = 255, message = "Series name must not exceed 255 characters")
    @Schema(description = "Updated series name")
    private String name;

    @Size(max = 10000, message = "Description is too long")
    @Schema(description = "Updated series description")
    private String description;

    // ==================== RECURRENCE SETTINGS ====================

    @Schema(description = "Updated recurrence pattern")
    private RecurrencePattern recurrencePattern;

    @Min(value = 1, message = "Recurrence interval must be at least 1")
    @Schema(description = "Updated recurrence interval")
    private Integer recurrenceInterval;

    @Schema(description = "Updated recurrence end type")
    private RecurrenceEndType recurrenceEndType;

    @Schema(description = "Updated series end date")
    private LocalDateTime seriesEndDate;

    @Min(value = 1, message = "Max occurrences must be at least 1")
    @Schema(description = "Updated maximum occurrences")
    private Integer maxOccurrences;

    // ==================== WEEKLY RECURRENCE ====================

    @Schema(description = "Updated days of week for WEEKLY recurrence")
    private List<DayOfWeek> daysOfWeek;

    // ==================== MONTHLY RECURRENCE ====================

    @Schema(description = "Updated day of month for MONTHLY recurrence")
    private Integer dayOfMonth;

    @Schema(description = "Updated week of month for MONTHLY recurrence")
    private Integer weekOfMonth;

    @Schema(description = "Updated day of week for nth weekday MONTHLY recurrence")
    private DayOfWeek dayOfWeekForMonthly;

    // ==================== EVENT DEFAULTS ====================

    @Schema(description = "Updated default duration in minutes")
    private Integer defaultDurationMinutes;

    @Schema(description = "Updated default start time")
    private LocalTime defaultStartTime;

    @Schema(description = "Updated timezone")
    private String timezone;

    // ==================== STATUS ====================

    @Schema(description = "Whether the series is active")
    private Boolean isActive;

    @Schema(description = "Whether to auto-generate future occurrences")
    private Boolean autoGenerate;

    @Schema(description = "Updated days ahead to auto-generate")
    private Integer autoGenerateDaysAhead;
}
