package eventplanner.features.event.dto.response;

import eventplanner.features.event.entity.EventSeries;
import eventplanner.features.event.enums.RecurrenceEndType;
import eventplanner.features.event.enums.RecurrencePattern;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

/**
 * Response DTO for event series.
 */
@Schema(description = "Event series details")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EventSeriesResponse {

    @Schema(description = "Series ID")
    private UUID id;

    @Schema(description = "Series name")
    private String name;

    @Schema(description = "Series description")
    private String description;

    @Schema(description = "Owner ID")
    private UUID ownerId;

    // ==================== RECURRENCE SETTINGS ====================

    @Schema(description = "Recurrence pattern")
    private RecurrencePattern recurrencePattern;

    @Schema(description = "Recurrence interval")
    private Integer recurrenceInterval;

    @Schema(description = "Recurrence end type")
    private RecurrenceEndType recurrenceEndType;

    @Schema(description = "Series start date")
    private LocalDateTime seriesStartDate;

    @Schema(description = "Series end date")
    private LocalDateTime seriesEndDate;

    @Schema(description = "Maximum occurrences")
    private Integer maxOccurrences;

    @Schema(description = "Occurrences generated so far")
    private Integer occurrencesGenerated;

    // ==================== WEEKLY RECURRENCE ====================

    @Schema(description = "Days of week for WEEKLY recurrence")
    private List<DayOfWeek> daysOfWeek;

    // ==================== MONTHLY RECURRENCE ====================

    @Schema(description = "Day of month for MONTHLY recurrence")
    private Integer dayOfMonth;

    @Schema(description = "Week of month for MONTHLY recurrence")
    private Integer weekOfMonth;

    @Schema(description = "Day of week for nth weekday MONTHLY recurrence")
    private String dayOfWeekForMonthly;

    // ==================== EVENT DEFAULTS ====================

    @Schema(description = "Default duration in minutes")
    private Integer defaultDurationMinutes;

    @Schema(description = "Default start time")
    private LocalTime defaultStartTime;

    @Schema(description = "Timezone")
    private String timezone;

    @Schema(description = "Master event ID (template event)")
    private UUID masterEventId;

    // ==================== STATUS ====================

    @Schema(description = "Whether the series is active")
    private Boolean isActive;

    @Schema(description = "Whether auto-generation is enabled")
    private Boolean autoGenerate;

    @Schema(description = "Days ahead to auto-generate")
    private Integer autoGenerateDaysAhead;

    // ==================== COMPUTED FIELDS ====================

    @Schema(description = "Total events in the series")
    private Integer totalEvents;

    @Schema(description = "Upcoming events count")
    private Integer upcomingEventsCount;

    @Schema(description = "Next occurrence date")
    private LocalDateTime nextOccurrenceDate;

    @Schema(description = "Whether more occurrences can be generated")
    private Boolean canGenerateMore;

    // ==================== TIMESTAMPS ====================

    @Schema(description = "Creation timestamp")
    private LocalDateTime createdAt;

    @Schema(description = "Last update timestamp")
    private LocalDateTime updatedAt;

    /**
     * Convert entity to response DTO.
     */
    public static EventSeriesResponse from(EventSeries series) {
        if (series == null) {
            return null;
        }

        return EventSeriesResponse.builder()
                .id(series.getId())
                .name(series.getName())
                .description(series.getDescription())
                .ownerId(series.getOwner() != null ? series.getOwner().getId() : null)
                .recurrencePattern(series.getRecurrencePattern())
                .recurrenceInterval(series.getRecurrenceInterval())
                .recurrenceEndType(series.getRecurrenceEndType())
                .seriesStartDate(series.getSeriesStartDate())
                .seriesEndDate(series.getSeriesEndDate())
                .maxOccurrences(series.getMaxOccurrences())
                .occurrencesGenerated(series.getOccurrencesGenerated())
                .daysOfWeek(series.getDaysOfWeekList())
                .dayOfMonth(series.getDayOfMonth())
                .weekOfMonth(series.getWeekOfMonth())
                .dayOfWeekForMonthly(series.getDayOfWeekForMonthly())
                .defaultDurationMinutes(series.getDefaultDurationMinutes())
                .defaultStartTime(series.getDefaultStartTime())
                .timezone(series.getTimezone())
                .masterEventId(series.getMasterEventId())
                .isActive(series.getIsActive())
                .autoGenerate(series.getAutoGenerate())
                .autoGenerateDaysAhead(series.getAutoGenerateDaysAhead())
                .canGenerateMore(series.canGenerateMore())
                .createdAt(series.getCreatedAt())
                .updatedAt(series.getUpdatedAt())
                .build();
    }

    /**
     * Convert entity to response DTO with event counts.
     */
    public static EventSeriesResponse from(EventSeries series, int totalEvents, int upcomingEvents, LocalDateTime nextOccurrence) {
        EventSeriesResponse response = from(series);
        if (response != null) {
            response.setTotalEvents(totalEvents);
            response.setUpcomingEventsCount(upcomingEvents);
            response.setNextOccurrenceDate(nextOccurrence);
        }
        return response;
    }
}
