package eventplanner.features.event.service;

import eventplanner.common.exception.exceptions.BadRequestException;
import eventplanner.common.exception.exceptions.ForbiddenException;
import eventplanner.common.exception.exceptions.ResourceNotFoundException;
import eventplanner.features.event.dto.request.CreateEventSeriesRequest;
import eventplanner.features.event.dto.request.GenerateOccurrencesRequest;
import eventplanner.features.event.dto.request.UpdateEventSeriesRequest;
import eventplanner.features.event.dto.response.EventSeriesResponse;
import eventplanner.features.event.dto.response.GenerateOccurrencesResponse;
import eventplanner.features.event.entity.Event;
import eventplanner.features.event.entity.EventSeries;
import eventplanner.features.event.entity.Venue;
import eventplanner.features.event.enums.EventAccessType;
import eventplanner.features.event.enums.EventStatus;
import eventplanner.features.event.enums.RecurrenceEndType;
import eventplanner.features.event.enums.RecurrencePattern;
import eventplanner.features.event.enums.SeriesUpdateScope;
import eventplanner.features.event.repository.EventRepository;
import eventplanner.features.event.repository.EventSeriesRepository;
import eventplanner.security.auth.entity.UserAccount;
import eventplanner.security.auth.repository.UserAccountRepository;
import eventplanner.security.auth.service.UserPrincipal;
import eventplanner.security.authorization.service.AuthorizationService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.temporal.TemporalAdjusters;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Service for managing event series and recurring events.
 */
@Service
@Transactional
@RequiredArgsConstructor
@Slf4j
public class EventSeriesService {

    private final EventSeriesRepository seriesRepository;
    private final EventRepository eventRepository;
    private final UserAccountRepository userAccountRepository;
    private final AuthorizationService authorizationService;

    private static final int MAX_OCCURRENCES_PER_GENERATION = 100;
    private static final int DEFAULT_INITIAL_OCCURRENCES = 4;

    // ==================== CREATE SERIES ====================

    /**
     * Create a new event series with initial occurrences.
     */
    public EventSeriesResponse createSeries(CreateEventSeriesRequest request, UserPrincipal principal) {
        validateCreateRequest(request);

        UserAccount owner = userAccountRepository.findById(principal.getId())
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // Create the series
        EventSeries series = new EventSeries();
        series.setName(request.getName());
        series.setDescription(request.getDescription());
        series.setOwner(owner);
        
        // Recurrence settings
        series.setRecurrencePattern(request.getRecurrencePattern());
        series.setRecurrenceInterval(request.getRecurrenceInterval() != null ? request.getRecurrenceInterval() : 1);
        series.setRecurrenceEndType(request.getRecurrenceEndType());
        series.setSeriesStartDate(request.getSeriesStartDate());
        series.setSeriesEndDate(request.getSeriesEndDate());
        series.setMaxOccurrences(request.getMaxOccurrences());
        series.setOccurrencesGenerated(0);

        // Weekly settings
        if (request.getDaysOfWeek() != null && !request.getDaysOfWeek().isEmpty()) {
            series.setDaysOfWeekList(request.getDaysOfWeek());
        }

        // Monthly settings
        series.setDayOfMonth(request.getDayOfMonth());
        series.setWeekOfMonth(request.getWeekOfMonth());
        if (request.getDayOfWeekForMonthly() != null) {
            series.setDayOfWeekForMonthly(request.getDayOfWeekForMonthly().name());
        }

        // Event defaults
        series.setDefaultDurationMinutes(request.getDefaultDurationMinutes());
        series.setDefaultStartTime(request.getDefaultStartTime() != null 
                ? request.getDefaultStartTime() 
                : request.getSeriesStartDate().toLocalTime());
        series.setTimezone(request.getTimezone() != null ? request.getTimezone() : "UTC");

        // Auto-generation settings
        series.setAutoGenerate(request.getAutoGenerate() != null ? request.getAutoGenerate() : true);
        series.setAutoGenerateDaysAhead(request.getAutoGenerateDaysAhead() != null 
                ? request.getAutoGenerateDaysAhead() : 90);
        series.setIsActive(true);

        EventSeries savedSeries = seriesRepository.save(series);
        log.info("Created event series '{}' (ID: {}) for user {}", 
                savedSeries.getName(), savedSeries.getId(), principal.getId());

        // Generate initial occurrences
        int initialCount = request.getInitialOccurrencesToGenerate() != null 
                ? request.getInitialOccurrencesToGenerate() 
                : DEFAULT_INITIAL_OCCURRENCES;
        
        if (initialCount > 0) {
            generateOccurrencesInternal(savedSeries, initialCount, null, false);
        }

        return toResponseWithCounts(savedSeries);
    }

    // ==================== READ SERIES ====================

    /**
     * Get series by ID.
     */
    public EventSeriesResponse getSeriesById(UUID seriesId, UserPrincipal principal) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesAccess(series, principal);
        return toResponseWithCounts(series);
    }

    /**
     * List series for the current user.
     */
    public Page<EventSeriesResponse> listMySeries(UserPrincipal principal, int page, int size, Boolean activeOnly) {
        Pageable pageable = PageRequest.of(page, Math.min(size, 100), Sort.by(Sort.Direction.DESC, "createdAt"));
        
        Page<EventSeries> seriesPage;
        if (Boolean.TRUE.equals(activeOnly)) {
            seriesPage = seriesRepository.findByOwnerIdAndIsActiveTrue(principal.getId(), pageable);
        } else {
            seriesPage = seriesRepository.findByOwnerId(principal.getId(), pageable);
        }

        return seriesPage.map(this::toResponseWithCounts);
    }

    /**
     * List events in a series.
     */
    public Page<Event> listSeriesEvents(UUID seriesId, UserPrincipal principal, int page, int size, Boolean upcomingOnly) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesAccess(series, principal);

        Pageable pageable = PageRequest.of(page, Math.min(size, 100), Sort.by(Sort.Direction.ASC, "startDateTime"));
        
        if (Boolean.TRUE.equals(upcomingOnly)) {
            return eventRepository.findAll((root, query, cb) -> {
                return cb.and(
                        cb.equal(root.get("parentSeries").get("id"), seriesId),
                        cb.greaterThanOrEqualTo(root.get("startDateTime"), LocalDateTime.now())
                );
            }, pageable);
        }

        return eventRepository.findAll((root, query, cb) -> 
                cb.equal(root.get("parentSeries").get("id"), seriesId), pageable);
    }

    // ==================== UPDATE SERIES ====================

    /**
     * Update series settings.
     */
    public EventSeriesResponse updateSeries(UUID seriesId, UpdateEventSeriesRequest request, UserPrincipal principal) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesOwnership(series, principal);

        // Update series fields
        if (request.getName() != null) {
            series.setName(request.getName());
        }
        if (request.getDescription() != null) {
            series.setDescription(request.getDescription());
        }
        if (request.getRecurrencePattern() != null) {
            series.setRecurrencePattern(request.getRecurrencePattern());
        }
        if (request.getRecurrenceInterval() != null) {
            series.setRecurrenceInterval(request.getRecurrenceInterval());
        }
        if (request.getRecurrenceEndType() != null) {
            series.setRecurrenceEndType(request.getRecurrenceEndType());
        }
        if (request.getSeriesEndDate() != null) {
            series.setSeriesEndDate(request.getSeriesEndDate());
        }
        if (request.getMaxOccurrences() != null) {
            series.setMaxOccurrences(request.getMaxOccurrences());
        }
        if (request.getDaysOfWeek() != null) {
            series.setDaysOfWeekList(request.getDaysOfWeek());
        }
        if (request.getDayOfMonth() != null) {
            series.setDayOfMonth(request.getDayOfMonth());
        }
        if (request.getWeekOfMonth() != null) {
            series.setWeekOfMonth(request.getWeekOfMonth());
        }
        if (request.getDayOfWeekForMonthly() != null) {
            series.setDayOfWeekForMonthly(request.getDayOfWeekForMonthly().name());
        }
        if (request.getDefaultDurationMinutes() != null) {
            series.setDefaultDurationMinutes(request.getDefaultDurationMinutes());
        }
        if (request.getDefaultStartTime() != null) {
            series.setDefaultStartTime(request.getDefaultStartTime());
        }
        if (request.getTimezone() != null) {
            series.setTimezone(request.getTimezone());
        }
        if (request.getIsActive() != null) {
            series.setIsActive(request.getIsActive());
        }
        if (request.getAutoGenerate() != null) {
            series.setAutoGenerate(request.getAutoGenerate());
        }
        if (request.getAutoGenerateDaysAhead() != null) {
            series.setAutoGenerateDaysAhead(request.getAutoGenerateDaysAhead());
        }

        EventSeries updated = seriesRepository.save(series);

        // If updating future events, cascade changes
        SeriesUpdateScope scope = request.getUpdateScope() != null 
                ? request.getUpdateScope() 
                : SeriesUpdateScope.THIS_AND_FUTURE;
        
        if (scope == SeriesUpdateScope.THIS_AND_FUTURE || scope == SeriesUpdateScope.ALL_OCCURRENCES) {
            cascadeUpdatesToEvents(updated, request, scope);
        }

        log.info("Updated event series '{}' (ID: {})", updated.getName(), updated.getId());
        return toResponseWithCounts(updated);
    }

    // ==================== DELETE / CANCEL SERIES ====================

    /**
     * Cancel/deactivate a series.
     */
    public void cancelSeries(UUID seriesId, UserPrincipal principal, boolean cancelFutureEvents) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesOwnership(series, principal);

        series.setIsActive(false);
        seriesRepository.save(series);

        if (cancelFutureEvents) {
            // Cancel all future events in the series
            List<Event> futureEvents = eventRepository.findAll((root, query, cb) -> 
                    cb.and(
                            cb.equal(root.get("parentSeries").get("id"), seriesId),
                            cb.greaterThanOrEqualTo(root.get("startDateTime"), LocalDateTime.now()),
                            cb.notEqual(root.get("eventStatus"), EventStatus.CANCELLED)
                    ));

            for (Event event : futureEvents) {
                event.setEventStatus(EventStatus.CANCELLED);
                eventRepository.save(event);
            }

            log.info("Cancelled series '{}' (ID: {}) and {} future events", 
                    series.getName(), seriesId, futureEvents.size());
        } else {
            log.info("Deactivated series '{}' (ID: {})", series.getName(), seriesId);
        }
    }

    /**
     * Delete a series and optionally its events.
     */
    public void deleteSeries(UUID seriesId, UserPrincipal principal, boolean deleteEvents) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesOwnership(series, principal);

        if (deleteEvents) {
            // Delete all events in the series
            List<Event> events = eventRepository.findAll((root, query, cb) -> 
                    cb.equal(root.get("parentSeries").get("id"), seriesId));
            
            for (Event event : events) {
                event.setParentSeries(null);
                event.softDelete();
                eventRepository.save(event);
            }
            log.info("Soft-deleted {} events from series '{}'", events.size(), series.getName());
        } else {
            // Just detach events from the series
            List<Event> events = eventRepository.findAll((root, query, cb) -> 
                    cb.equal(root.get("parentSeries").get("id"), seriesId));
            
            for (Event event : events) {
                event.setParentSeries(null);
                eventRepository.save(event);
            }
            log.info("Detached {} events from series '{}'", events.size(), series.getName());
        }

        seriesRepository.delete(series);
        log.info("Deleted series '{}' (ID: {})", series.getName(), seriesId);
    }

    // ==================== GENERATE OCCURRENCES ====================

    /**
     * Generate occurrences for a series.
     */
    public GenerateOccurrencesResponse generateOccurrences(UUID seriesId, GenerateOccurrencesRequest request, 
                                                           UserPrincipal principal) {
        EventSeries series = requireSeries(seriesId);
        requireSeriesOwnership(series, principal);

        if (!series.canGenerateMore() && !Boolean.TRUE.equals(request.getForceGeneration())) {
            throw new BadRequestException("Series has reached its occurrence limit");
        }

        int count = request.getCount() != null ? request.getCount() : DEFAULT_INITIAL_OCCURRENCES;
        LocalDateTime untilDate = request.getUntilDate();
        boolean skipConflicts = Boolean.TRUE.equals(request.getSkipConflicts());

        return generateOccurrencesInternal(series, count, untilDate, skipConflicts);
    }

    /**
     * Internal method to generate occurrences.
     */
    private GenerateOccurrencesResponse generateOccurrencesInternal(EventSeries series, int maxCount, 
                                                                     LocalDateTime untilDate, boolean skipConflicts) {
        List<UUID> generatedIds = new ArrayList<>();
        List<LocalDateTime> generatedDates = new ArrayList<>();
        List<GenerateOccurrencesResponse.SkippedOccurrence> skipped = new ArrayList<>();

        LocalDateTime currentDate = getNextOccurrenceDate(series);
        int generated = 0;

        while (generated < maxCount && generated < MAX_OCCURRENCES_PER_GENERATION) {
            // Check end conditions
            if (!series.canGenerateMore()) {
                break;
            }
            if (untilDate != null && currentDate.isAfter(untilDate)) {
                break;
            }
            if (series.getRecurrenceEndType() == RecurrenceEndType.BY_DATE 
                    && series.getSeriesEndDate() != null 
                    && currentDate.isAfter(series.getSeriesEndDate())) {
                break;
            }

            // Create the event occurrence
            Event event = createOccurrence(series, currentDate, series.getOccurrencesGenerated() + 1);
            Event savedEvent = eventRepository.save(event);
            
            generatedIds.add(savedEvent.getId());
            generatedDates.add(currentDate);
            generated++;

            // Update series count
            series.incrementOccurrencesGenerated();
            seriesRepository.save(series);

            // Calculate next occurrence date
            currentDate = calculateNextOccurrenceDate(series, currentDate);
        }

        log.info("Generated {} occurrences for series '{}' (ID: {})", 
                generated, series.getName(), series.getId());

        return GenerateOccurrencesResponse.builder()
                .seriesId(series.getId())
                .generatedCount(generated)
                .skippedCount(skipped.size())
                .totalOccurrences(series.getOccurrencesGenerated())
                .generatedEventIds(generatedIds)
                .generatedDates(generatedDates)
                .skippedOccurrences(skipped)
                .canGenerateMore(series.canGenerateMore())
                .nextAvailableDate(calculateNextOccurrenceDate(series, currentDate))
                .message(String.format("Generated %d occurrence(s) for series '%s'", generated, series.getName()))
                .build();
    }

    /**
     * Create a single event occurrence from series settings.
     */
    private Event createOccurrence(EventSeries series, LocalDateTime startDateTime, int occurrenceNumber) {
        Event event = new Event();
        event.setName(series.getName());
        event.setDescription(series.getDescription());
        event.setOwner(series.getOwner());
        event.setParentSeries(series);
        event.setSeriesOccurrenceNumber(occurrenceNumber);
        event.setIsSeriesMaster(false);
        event.setIsSeriesException(false);
        event.setOriginalStartDateTime(startDateTime);

        // Set dates
        event.setStartDateTime(startDateTime);
        if (series.getDefaultDurationMinutes() != null) {
            event.setEndDateTime(startDateTime.plusMinutes(series.getDefaultDurationMinutes()));
        }

        // Copy settings from master event if available
        if (series.getMasterEventId() != null) {
            eventRepository.findById(series.getMasterEventId()).ifPresent(master -> {
                copyEventSettings(master, event);
            });
        } else {
            // Use default settings
            event.setEventStatus(EventStatus.PUBLISHED);
            event.setAccessType(EventAccessType.OPEN);
            event.setIsPublic(true);
            event.setRequiresApproval(false);
        }

        return event;
    }

    /**
     * Copy settings from master event to new occurrence.
     */
    private void copyEventSettings(Event master, Event occurrence) {
        occurrence.setEventType(master.getEventType());
        occurrence.setEventStatus(EventStatus.PUBLISHED);
        occurrence.setAccessType(master.getAccessType());
        occurrence.setIsPublic(master.getIsPublic());
        occurrence.setRequiresApproval(master.getRequiresApproval());
        occurrence.setCapacity(master.getCapacity());
        occurrence.setHashtag(master.getHashtag());
        occurrence.setTheme(master.getTheme());
        occurrence.setObjectives(master.getObjectives());
        occurrence.setTargetAudience(master.getTargetAudience());
        occurrence.setVenueRequirements(master.getVenueRequirements());
        occurrence.setTechnicalRequirements(master.getTechnicalRequirements());
        occurrence.setAccessibilityFeatures(master.getAccessibilityFeatures());
        occurrence.setMetadata(master.getMetadata());
        
        // Copy venue
        if (master.getVenue() != null) {
            Venue venue = new Venue();
            venue.setAddress(master.getVenue().getAddress());
            venue.setCity(master.getVenue().getCity());
            venue.setState(master.getVenue().getState());
            venue.setCountry(master.getVenue().getCountry());
            venue.setZipCode(master.getVenue().getZipCode());
            venue.setLatitude(master.getVenue().getLatitude());
            venue.setLongitude(master.getVenue().getLongitude());
            venue.setGooglePlaceId(master.getVenue().getGooglePlaceId());
            venue.setGooglePlaceData(master.getVenue().getGooglePlaceData());
            occurrence.setVenue(venue);
        }
    }

    // ==================== DATE CALCULATION ====================

    /**
     * Get the next occurrence date for a series.
     */
    private LocalDateTime getNextOccurrenceDate(EventSeries series) {
        // Find the last event in the series
        List<Event> existingEvents = eventRepository.findAll((root, query, cb) -> {
            query.orderBy(cb.desc(root.get("startDateTime")));
            return cb.equal(root.get("parentSeries").get("id"), series.getId());
        });

        if (existingEvents.isEmpty()) {
            // First occurrence uses series start date
            return series.getSeriesStartDate();
        }

        // Calculate next date from last occurrence
        LocalDateTime lastDate = existingEvents.get(0).getStartDateTime();
        return calculateNextOccurrenceDate(series, lastDate);
    }

    /**
     * Calculate the next occurrence date based on recurrence pattern.
     */
    private LocalDateTime calculateNextOccurrenceDate(EventSeries series, LocalDateTime fromDate) {
        int interval = series.getRecurrenceInterval() != null ? series.getRecurrenceInterval() : 1;
        LocalTime time = series.getDefaultStartTime() != null 
                ? series.getDefaultStartTime() 
                : fromDate.toLocalTime();

        switch (series.getRecurrencePattern()) {
            case DAILY:
                return fromDate.plusDays(interval).with(time);

            case WEEKLY:
                return calculateNextWeeklyDate(series, fromDate, interval, time);

            case MONTHLY:
                return calculateNextMonthlyDate(series, fromDate, interval, time);

            case YEARLY:
                return fromDate.plusYears(interval).with(time);

            case CUSTOM:
            default:
                // For custom, just add interval days
                return fromDate.plusDays(interval).with(time);
        }
    }

    /**
     * Calculate next weekly occurrence date.
     */
    private LocalDateTime calculateNextWeeklyDate(EventSeries series, LocalDateTime fromDate, 
                                                   int interval, LocalTime time) {
        List<DayOfWeek> days = series.getDaysOfWeekList();
        if (days.isEmpty()) {
            // Default to same day of week
            return fromDate.plusWeeks(interval).with(time);
        }

        // Find next day in the week, or first day of next interval week
        LocalDateTime candidate = fromDate.plusDays(1);
        
        // Look for next day in current week
        while (candidate.getDayOfWeek() != DayOfWeek.MONDAY || candidate.equals(fromDate.plusDays(1))) {
            if (days.contains(candidate.getDayOfWeek())) {
                return candidate.with(time);
            }
            candidate = candidate.plusDays(1);
            if (candidate.isAfter(fromDate.plusDays(7))) {
                break;
            }
        }

        // Move to first day of next interval week
        LocalDateTime nextWeekStart = fromDate.with(TemporalAdjusters.next(DayOfWeek.MONDAY))
                .plusWeeks(interval - 1);
        for (DayOfWeek day : days) {
            LocalDateTime nextOccurrence = nextWeekStart.with(TemporalAdjusters.nextOrSame(day)).with(time);
            if (nextOccurrence.isAfter(fromDate)) {
                return nextOccurrence;
            }
        }

        return nextWeekStart.with(time);
    }

    /**
     * Calculate next monthly occurrence date.
     */
    private LocalDateTime calculateNextMonthlyDate(EventSeries series, LocalDateTime fromDate, 
                                                    int interval, LocalTime time) {
        LocalDateTime nextMonth = fromDate.plusMonths(interval);

        if (series.getDayOfMonth() != null) {
            // Specific day of month
            int day = Math.min(series.getDayOfMonth(), nextMonth.toLocalDate().lengthOfMonth());
            return nextMonth.withDayOfMonth(day).with(time);
        }

        if (series.getWeekOfMonth() != null && series.getDayOfWeekForMonthly() != null) {
            // Nth weekday of month
            DayOfWeek dayOfWeek = DayOfWeek.valueOf(series.getDayOfWeekForMonthly());
            int weekOfMonth = series.getWeekOfMonth();

            LocalDateTime firstOfMonth = nextMonth.withDayOfMonth(1);
            LocalDateTime nthWeekday;

            if (weekOfMonth == 5) {
                // Last occurrence of the weekday
                nthWeekday = firstOfMonth.with(TemporalAdjusters.lastInMonth(dayOfWeek));
            } else {
                nthWeekday = firstOfMonth.with(TemporalAdjusters.dayOfWeekInMonth(weekOfMonth, dayOfWeek));
            }

            return nthWeekday.with(time);
        }

        // Default: same day of month as start date
        int day = Math.min(fromDate.getDayOfMonth(), nextMonth.toLocalDate().lengthOfMonth());
        return nextMonth.withDayOfMonth(day).with(time);
    }

    // ==================== HELPER METHODS ====================

    private void validateCreateRequest(CreateEventSeriesRequest request) {
        if (request.getRecurrenceEndType() == RecurrenceEndType.BY_DATE && request.getSeriesEndDate() == null) {
            throw new BadRequestException("Series end date is required when recurrence end type is BY_DATE");
        }
        if (request.getRecurrenceEndType() == RecurrenceEndType.BY_OCCURRENCES && request.getMaxOccurrences() == null) {
            throw new BadRequestException("Max occurrences is required when recurrence end type is BY_OCCURRENCES");
        }
        if (request.getRecurrencePattern() == RecurrencePattern.WEEKLY 
                && (request.getDaysOfWeek() == null || request.getDaysOfWeek().isEmpty())) {
            // Default to the day of week from start date
            request.setDaysOfWeek(List.of(request.getSeriesStartDate().getDayOfWeek()));
        }
    }

    private EventSeries requireSeries(UUID seriesId) {
        return seriesRepository.findById(seriesId)
                .orElseThrow(() -> new ResourceNotFoundException("Event series not found: " + seriesId));
    }

    private void requireSeriesAccess(EventSeries series, UserPrincipal principal) {
        if (!series.getOwner().getId().equals(principal.getId()) 
                && !authorizationService.isAdmin(principal)) {
            throw new ForbiddenException("Access denied to event series");
        }
    }

    private void requireSeriesOwnership(EventSeries series, UserPrincipal principal) {
        if (!series.getOwner().getId().equals(principal.getId()) 
                && !authorizationService.isAdmin(principal)) {
            throw new ForbiddenException("Only the series owner can perform this action");
        }
    }

    private void cascadeUpdatesToEvents(EventSeries series, UpdateEventSeriesRequest request, 
                                         SeriesUpdateScope scope) {
        List<Event> eventsToUpdate;

        if (scope == SeriesUpdateScope.THIS_AND_FUTURE) {
            eventsToUpdate = eventRepository.findAll((root, query, cb) -> 
                    cb.and(
                            cb.equal(root.get("parentSeries").get("id"), series.getId()),
                            cb.greaterThanOrEqualTo(root.get("startDateTime"), LocalDateTime.now()),
                            cb.equal(root.get("isSeriesException"), false)
                    ));
        } else {
            eventsToUpdate = eventRepository.findAll((root, query, cb) -> 
                    cb.and(
                            cb.equal(root.get("parentSeries").get("id"), series.getId()),
                            cb.equal(root.get("isSeriesException"), false)
                    ));
        }

        for (Event event : eventsToUpdate) {
            if (request.getName() != null) {
                event.setName(request.getName());
            }
            // Update duration if changed
            if (request.getDefaultDurationMinutes() != null && event.getStartDateTime() != null) {
                event.setEndDateTime(event.getStartDateTime().plusMinutes(request.getDefaultDurationMinutes()));
            }
            eventRepository.save(event);
        }

        log.info("Cascaded updates to {} events in series '{}'", eventsToUpdate.size(), series.getName());
    }

    private EventSeriesResponse toResponseWithCounts(EventSeries series) {
        // Count total and upcoming events
        long totalEvents = eventRepository.count((root, query, cb) -> 
                cb.equal(root.get("parentSeries").get("id"), series.getId()));
        
        long upcomingEvents = eventRepository.count((root, query, cb) -> 
                cb.and(
                        cb.equal(root.get("parentSeries").get("id"), series.getId()),
                        cb.greaterThanOrEqualTo(root.get("startDateTime"), LocalDateTime.now())
                ));

        // Find next occurrence
        List<Event> nextEvents = eventRepository.findAll((root, query, cb) -> {
            query.orderBy(cb.asc(root.get("startDateTime")));
            return cb.and(
                    cb.equal(root.get("parentSeries").get("id"), series.getId()),
                    cb.greaterThanOrEqualTo(root.get("startDateTime"), LocalDateTime.now())
            );
        });
        LocalDateTime nextOccurrence = nextEvents.isEmpty() ? null : nextEvents.get(0).getStartDateTime();

        return EventSeriesResponse.from(series, (int) totalEvents, (int) upcomingEvents, nextOccurrence);
    }
}
