package eventplanner.features.event.service;

import eventplanner.features.event.dto.request.GenerateOccurrencesRequest;
import eventplanner.features.event.dto.response.GenerateOccurrencesResponse;
import eventplanner.features.event.entity.Event;
import eventplanner.features.event.entity.EventSeries;
import eventplanner.features.event.repository.EventRepository;
import eventplanner.features.event.repository.EventSeriesRepository;
import eventplanner.security.auth.service.UserPrincipal;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Scheduled service for auto-generating event series occurrences.
 * Runs periodically to ensure series have events generated ahead of time.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EventSeriesSchedulerService {

    private final EventSeriesRepository seriesRepository;
    private final EventRepository eventRepository;
    private final EventSeriesService seriesService;

    /**
     * Scheduled task to auto-generate occurrences for active series.
     * Runs daily at 2 AM to generate events up to each series' configured horizon.
     */
    @Scheduled(cron = "${event.series.auto-generate.cron:0 0 2 * * *}")
    @Transactional
    public void autoGenerateOccurrences() {
        log.info("Starting scheduled auto-generation of series occurrences");
        
        LocalDateTime now = LocalDateTime.now();
        List<EventSeries> activeSeries = seriesRepository.findActiveSeriesNeedingGeneration(now);
        
        int totalGenerated = 0;
        int seriesProcessed = 0;
        int seriesWithErrors = 0;

        for (EventSeries series : activeSeries) {
            try {
                int generated = processSeriesGeneration(series, now);
                totalGenerated += generated;
                seriesProcessed++;
                
                if (generated > 0) {
                    log.debug("Generated {} occurrences for series '{}' (ID: {})", 
                            generated, series.getName(), series.getId());
                }
            } catch (Exception e) {
                seriesWithErrors++;
                log.error("Error generating occurrences for series '{}' (ID: {}): {}", 
                        series.getName(), series.getId(), e.getMessage(), e);
            }
        }

        log.info("Completed auto-generation: {} series processed, {} total occurrences generated, {} errors",
                seriesProcessed, totalGenerated, seriesWithErrors);
    }

    /**
     * Process a single series and generate occurrences if needed.
     * 
     * @param series The series to process
     * @param now Current time
     * @return Number of occurrences generated
     */
    private int processSeriesGeneration(EventSeries series, LocalDateTime now) {
        if (!Boolean.TRUE.equals(series.getAutoGenerate())) {
            return 0;
        }

        if (!series.canGenerateMore()) {
            return 0;
        }

        // Calculate the horizon - how far ahead we should have events
        int daysAhead = series.getAutoGenerateDaysAhead() != null ? series.getAutoGenerateDaysAhead() : 90;
        LocalDateTime horizon = now.plusDays(daysAhead);

        // Find the last generated event
        List<Event> lastEvents = eventRepository.findAll((root, query, cb) -> {
            query.orderBy(cb.desc(root.get("startDateTime")));
            return cb.equal(root.get("parentSeries").get("id"), series.getId());
        });

        LocalDateTime lastEventDate = lastEvents.isEmpty() 
                ? series.getSeriesStartDate().minusDays(1) 
                : lastEvents.get(0).getStartDateTime();

        // If last event is already past the horizon, no need to generate
        if (lastEventDate != null && lastEventDate.isAfter(horizon)) {
            return 0;
        }

        // Calculate how many events we need to generate to reach the horizon
        int eventsToGenerate = calculateEventsNeeded(series, lastEventDate, horizon);
        
        if (eventsToGenerate <= 0) {
            return 0;
        }

        // Cap at a reasonable number per run to avoid overloading
        eventsToGenerate = Math.min(eventsToGenerate, 20);

        // Generate occurrences using the service
        // Create a system principal for scheduled operations
        UserPrincipal systemPrincipal = createSystemPrincipal(series);
        
        GenerateOccurrencesRequest request = new GenerateOccurrencesRequest();
        request.setCount(eventsToGenerate);
        request.setUntilDate(horizon);
        request.setSkipConflicts(false);
        request.setForceGeneration(false);

        try {
            GenerateOccurrencesResponse response = seriesService.generateOccurrences(
                    series.getId(), request, systemPrincipal);
            return response.getGeneratedCount();
        } catch (Exception e) {
            log.warn("Failed to generate occurrences for series {}: {}", series.getId(), e.getMessage());
            return 0;
        }
    }

    /**
     * Estimate how many events need to be generated to reach the horizon.
     */
    private int calculateEventsNeeded(EventSeries series, LocalDateTime lastDate, LocalDateTime horizon) {
        if (lastDate == null || lastDate.isAfter(horizon)) {
            return 0;
        }

        long daysBetween = java.time.Duration.between(lastDate, horizon).toDays();
        int interval = series.getRecurrenceInterval() != null ? series.getRecurrenceInterval() : 1;

        switch (series.getRecurrencePattern()) {
            case DAILY:
                return (int) Math.ceil((double) daysBetween / interval);
            case WEEKLY:
                int daysPerWeek = series.getDaysOfWeekList().isEmpty() ? 1 : series.getDaysOfWeekList().size();
                return (int) Math.ceil((double) daysBetween / (7 * interval) * daysPerWeek);
            case MONTHLY:
                return (int) Math.ceil((double) daysBetween / (30 * interval));
            case YEARLY:
                return (int) Math.ceil((double) daysBetween / (365 * interval));
            case CUSTOM:
            default:
                return (int) Math.ceil((double) daysBetween / interval);
        }
    }

    /**
     * Create a system principal for scheduled operations.
     * Uses the series owner's context.
     */
    private UserPrincipal createSystemPrincipal(EventSeries series) {
        // Return a principal that represents the series owner
        return new UserPrincipal(series.getOwner());
    }

    /**
     * Manual trigger to generate occurrences for all series.
     * Can be called from admin endpoints or management tools.
     */
    @Transactional
    public void triggerManualGeneration() {
        log.info("Manual trigger: Starting occurrence generation for all active series");
        autoGenerateOccurrences();
    }

    /**
     * Generate occurrences for a specific series.
     * Can be used when a series is created or updated.
     */
    @Transactional
    public int generateForSeries(EventSeries series) {
        if (series == null || !Boolean.TRUE.equals(series.getIsActive())) {
            return 0;
        }

        log.debug("Generating occurrences for series '{}' (ID: {})", series.getName(), series.getId());
        return processSeriesGeneration(series, LocalDateTime.now());
    }

    /**
     * Check if a series needs occurrence generation.
     */
    public boolean needsGeneration(EventSeries series) {
        if (series == null || !Boolean.TRUE.equals(series.getIsActive()) || !Boolean.TRUE.equals(series.getAutoGenerate())) {
            return false;
        }

        if (!series.canGenerateMore()) {
            return false;
        }

        int daysAhead = series.getAutoGenerateDaysAhead() != null ? series.getAutoGenerateDaysAhead() : 90;
        LocalDateTime horizon = LocalDateTime.now().plusDays(daysAhead);

        // Find the last event
        List<Event> lastEvents = eventRepository.findAll((root, query, cb) -> {
            query.orderBy(cb.desc(root.get("startDateTime")));
            return cb.equal(root.get("parentSeries").get("id"), series.getId());
        });

        if (lastEvents.isEmpty()) {
            return true; // No events yet, needs generation
        }

        LocalDateTime lastEventDate = lastEvents.get(0).getStartDateTime();
        return lastEventDate == null || lastEventDate.isBefore(horizon);
    }
}
