package eventplanner.features.event.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents an object stored externally (S3) for an event.
 *
 * Flow:
 * 1) Backend issues presigned upload (PUT) with deterministic objectKey
 * 2) Client uploads directly to S3
 * 3) Client calls "complete" endpoint to persist objectKey/resourceUrl + metadata here
 * 4) Backend generates presigned GET URLs for secure retrieval
 */
@Entity
@Table(name = "event_stored_objects")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EventStoredObject {

    /**
     * IMPORTANT: This id is assigned by the API (we use the mediaId returned in presign responses),
     * so it MUST NOT be generated by Hibernate.
     */
    @Id
    @Column(nullable = false)
    private UUID id;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Version
    private Long version;

    @Column(name = "event_id", nullable = false)
    private UUID eventId;

    /**
     * Logical purpose of this object (scales without schema changes).
     * Examples:
     * - event_media
     * - event_asset
     * - event_cover
     * - post_media
     */
    @Column(name = "purpose", nullable = false, length = 64)
    private String purpose;

    /**
     * The owning record id inside the event domain (eventId for event-level objects, postId for post media, etc).
     * Kept generic for scalability.
     */
    @Column(name = "owner_id", nullable = false)
    private UUID ownerId;

    @Column(name = "object_key", nullable = false, length = 512)
    private String objectKey;

    /**
     * A non-presigned URL (no query params) for display/reference.
     * NOTE: This may not be publicly accessible depending on bucket policy.
     */
    @Column(name = "resource_url", length = 2048)
    private String resourceUrl;

    @Column(name = "file_name", nullable = false, length = 255)
    private String fileName;

    @Column(name = "content_type", nullable = false, length = 255)
    private String contentType;

    @Column(name = "category", length = 100)
    private String category;

    @Column(name = "is_public", nullable = false)
    private Boolean isPublic = false;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Column(name = "tags", columnDefinition = "TEXT")
    private String tags;

    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata;

    @Column(name = "uploaded_by")
    private UUID uploadedBy;
}


